/* Additional record code for KinaseChain generated by the OpenModelica Compiler OpenModelica 1.22.0~15-g4f4bc9c. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "KinaseChain_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

