/* Simulation code for KinaseChain generated by the OpenModelica Compiler OpenModelica 1.22.0~15-g4f4bc9c. */
#if !defined(KinaseChain__MODEL_H)
#define KinaseChain__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "KinaseChain_functions.h"


extern void KinaseChain_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void KinaseChain_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int KinaseChain_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int KinaseChain_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int KinaseChain_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int KinaseChain_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int KinaseChain_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int KinaseChain_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int KinaseChain_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int KinaseChain_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int KinaseChain_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int KinaseChain_checkForAsserts(DATA *data, threadData_t *threadData);
extern int KinaseChain_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int KinaseChain_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int KinaseChain_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* KinaseChain_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* KinaseChain_relationDescription(int i);
extern void KinaseChain_function_initSample(DATA *data, threadData_t *threadData);
extern int KinaseChain_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int KinaseChain_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int KinaseChain_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int KinaseChain_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int KinaseChain_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int KinaseChain_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int KinaseChain_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int KinaseChain_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int KinaseChain_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int KinaseChain_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int KinaseChain_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int KinaseChain_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int KinaseChain_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int KinaseChain_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* KinaseChain_linear_model_frame(void);
extern const char* KinaseChain_linear_model_datarecovery_frame(void);
extern int KinaseChain_mayer(DATA* data, modelica_real** res, short *);
extern int KinaseChain_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int KinaseChain_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int KinaseChain_setInputData(DATA *data, const modelica_boolean file);
extern int KinaseChain_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void KinaseChain_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void KinaseChain_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int KinaseChain_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void KinaseChain_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void KinaseChain_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int KinaseChain_inputNames(DATA* data, char ** names);
extern int KinaseChain_dataReconciliationInputNames(DATA* data, char ** names);
extern int KinaseChain_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int KinaseChain_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int KinaseChain_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int KinaseChain_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "KinaseChain_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(KinaseChain__MODEL_H) */


